[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
# python_compile = true

[tools]
bat = "latest"
copier = "latest"
pre-commit = "latest"
python = ["3.13", "3.12", "3.11", "3.10"]
shellcheck = "latest"
shfmt = "latest"
usage = "latest"
uv = "latest"
# bats = "latest"
# black = "latest"
# cookiecutter = "latest"
# node = "latest"
# pipx = "latest"
# ruff = "latest"
# shfmt = "latest"
# terraform = "latest"
# tflint = "latest"
# tfsec = "latest"
"pipx:audible-cli" = "latest"
"pipx:ipython" = "latest"
"pipx:tmuxp" = "latest"
ruff = "latest"
# "go:github.com/containerscrew/tftools" = "latest"
# "pipx:flake8" = "latest"
# "pipx:isort" = "latest"
# "pipx:pylint" = "latest"
