[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
# python_compile = true

[tools]
bat = "latest"
bats = "latest"
black = "latest"
cookiecutter = "latest"
node = "latest"
pipx = "latest"
pre-commit = "latest"
python = ["3.14", "3.13", "3.12", "3.11", "3.10"]
ruff = "latest"
shellcheck = "latest"
shfmt = "latest"
terraform = "latest"
tflint = "latest"
tfsec = "latest"
usage = "latest"
uv = "latest"
