[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
# python_compile = true

[tools]
bat = "0.25.0"
bats = "1.12.0"
node = "24.7.0"
pipx = "1.7.1"
python = ["3.13.7", "3.12.11", "3.11.13", "3.10.18"]
ruff = "0.12.10"
shellcheck = "0.11.0"
shfmt = "3.12.0"
terraform = "1.13.1"
tflint = "0.58.1"
tfsec = "1.28.14"
